import {
  ActivityType,
  ObjectiveType,
  RelationshipFeeling,
  RelationshipStatus,
} from '../_model/model-sim.enums';

export const LABELS_OBJECTIVE_TYPES: Record<ObjectiveType, string> = {
  [ObjectiveType.HaveMeal]: 'Have a meal',
  [ObjectiveType.Rest]: 'Rest',
  [ObjectiveType.HaveFun]: 'Have fun',
  [ObjectiveType.Socialize]: 'Socialize',
  [ObjectiveType.GetMoney]: 'Get money',
  [ObjectiveType.SolveProblem]: 'Solve problem',
};

export const LABELS_ACTIVITY_TYPES: Record<ActivityType, string> = {
  [ActivityType.Eat]: 'Eat',
  [ActivityType.GoTo]: 'Go to',
  [ActivityType.Cook]: 'Cook',
  [ActivityType.Sleep]: 'Sleep',
  [ActivityType.Play]: 'Play',
  [ActivityType.Chat]: 'Chat',
  [ActivityType.Buy]: 'Buy',
  [ActivityType.Work]: 'Work',
  [ActivityType.AskForHelp]: 'Ask for help',
  [ActivityType.GroupMeal]: 'Go eat as a group',
  [ActivityType.PrepareMeal]: 'Prepare meal',
};

export const LABELS_FEELINGS: Record<RelationshipFeeling, string[]> = {
  [RelationshipFeeling.Admiration]: [
    'despises',
    'disdains',
    'dismisses',
    'admires',
    'greatly admires',
    'reveres',
  ],
  [RelationshipFeeling.Affection]: [
    'hates',
    'strongly dislikes',
    'dislikes',
    'likes',
    'really likes',
    'adores',
  ],
  [RelationshipFeeling.Attraction]: [
    'repulsed by',
    'strongly unattracted to',
    'not attracted to',
    'somewhat attracted to',
    'strongly attracted to',
    'irresistibly drawn to',
  ],
  [RelationshipFeeling.Love]: [
    'resents emotionally',
    'cold toward',
    'indifferent to',
    'has a crush on',
    'has romantic feelings for',
    'deeply in love with',
  ],
  [RelationshipFeeling.Gratitude]: [
    'resentful',
    'begrudging',
    'ungrateful',
    'grateful',
    'very grateful',
    'deeply thankful',
  ],
  [RelationshipFeeling.Trust]: [
    'deeply distrusts',
    'suspicious of',
    'skeptical of',
    'trusts',
    'strongly trusts',
    'completely trusts',
  ],
  [RelationshipFeeling.Jealousy]: [
    'indifferent',
    'slightly jealous',
    'jealous',
    'very jealous',
    'extremely jealous',
    'consumed by jealousy',
  ],
  [RelationshipFeeling.Envy]: [
    'content',
    'slightly envious',
    'envious',
    'very envious',
    'extremely envious',
    'bitterly envious',
  ],
  [RelationshipFeeling.Resentment]: [
    'at peace with',
    'slightly resentful',
    'resentful',
    'very resentful',
    'holds a grudge',
    'burns with resentment',
  ],
  [RelationshipFeeling.Annoyance]: [
    'unbothered by',
    'slightly annoyed',
    'annoyed',
    'very annoyed',
    'extremely irritated',
    'infuriated by',
  ],
  [RelationshipFeeling.Intimidation]: [
    'feels dominant over',
    'unintimidated by',
    'slightly intimidated by',
    'intimidated by',
    'very intimidated by',
    'terrified by',
  ],
  [RelationshipFeeling.Rivalry]: [
    'feels no rivalry',
    'minor competitor',
    'rival',
    'strong rival',
    'bitter rival',
    'mortal rival',
  ],
  [RelationshipFeeling.Respect]: [
    'disrespects',
    'dismisses',
    'neutral',
    'respects',
    'greatly respects',
    'reveres',
  ],
  [RelationshipFeeling.Suspicion]: [
    'trusts completely',
    'rarely suspicious',
    'mildly suspicious',
    'suspicious',
    'very suspicious',
    'deeply mistrustful',
  ],
  [RelationshipFeeling.Protectiveness]: [
    'indifferent to safety',
    'unconcerned',
    'somewhat protective',
    'protective',
    'very protective',
    'extremely protective',
  ],
};
